services:
  - type: web
    name: biodiversity-ontology-generator
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: SECRET_KEY
        generateValue: true
      - key: USE_GOOGLE_SHEETS
        value: true
      # Read the service account JSON from a file for security
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      # Optional: Default spreadsheet ID for logging
      - key: SPREADSHEET_ID
        value: ""