// Mock data for API simulation in preview environment

// Species mock data
export const mockSpecies = [
    {
      taxon_id: "giant-sequoia",
      common_name: "Giant Sequoia",
      accepted_scientific_name: "Sequoiadendron giganteum",
      species: "giganteum",
      family: "Cupressaceae",
      genus: "Sequoiadendron",
      general_description:
        "The giant sequoia is the world's most massive tree and largest living organism by volume. Giant sequoias grow to an average height of 50–85 m (164–279 ft) with trunk diameters ranging from 6–8 m (20–26 ft).",
      habitat: "Native to the Sierra Nevada mountains of California, USA",
      isResearched: true,
      conservation_status: "Vulnerable",
      fundingGoal: 2.5,
      fundingRaised: 0.75,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "coast-redwood",
      common_name: "Coast Redwood",
      accepted_scientific_name: "Sequoia sempervirens",
      species: "sempervirens",
      family: "Cupressaceae",
      genus: "Sequoia",
      general_description:
        "Coast redwoods are the tallest trees on Earth, reaching up to 115.5 m (379 ft) in height and 8.9 m (29 ft) in diameter. They are among the oldest living organisms on Earth.",
      habitat: "Native to the coastal regions of northern California and southern Oregon",
      isResearched: true,
      conservation_status: "Endangered",
      fundingGoal: 2.0,
      fundingRaised: 1.2,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "japanese-maple",
      common_name: "Japanese Maple",
      accepted_scientific_name: "Acer palmatum",
      species: "palmatum",
      family: "Sapindaceae",
      genus: "Acer",
      general_description:
        "Japanese maples are small, deciduous trees known for their graceful habit, autumn colors, and beautiful foliage. Many varieties have deeply lobed leaves with five, seven, or nine pointed lobes.",
      habitat: "Native to Japan, Korea, China, eastern Mongolia, and southeast Russia",
      isResearched: false,
      conservation_status: "Least Concern",
      fundingGoal: 1.5,
      fundingRaised: 0.3,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "baobab",
      common_name: "Baobab",
      accepted_scientific_name: "Adansonia",
      species: "digitata",
      family: "Malvaceae",
      genus: "Adansonia",
      general_description:
        "Baobabs are distinctive trees native to Madagascar, mainland Africa, and Australia. They have massive trunks that can store water and survive drought conditions.",
      habitat: "Native to the African continent, Madagascar, and Australia",
      isResearched: false,
      conservation_status: "Vulnerable",
      fundingGoal: 3.0,
      fundingRaised: 1.0,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "weeping-willow",
      common_name: "Weeping Willow",
      accepted_scientific_name: "Salix babylonica",
      species: "babylonica",
      family: "Salicaceae",
      genus: "Salix",
      general_description:
        "The weeping willow is a large, graceful tree with long, pendulous branches that sweep the ground. It is widely planted as an ornamental tree for its distinctive appearance.",
      habitat: "Native to northern China, but widely cultivated around the world",
      isResearched: false,
      conservation_status: "Least Concern",
      fundingGoal: 1.0,
      fundingRaised: 0.2,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "dawn-redwood",
      common_name: "Dawn Redwood",
      accepted_scientific_name: "Metasequoia glyptostroboides",
      species: "glyptostroboides",
      family: "Cupressaceae",
      genus: "Metasequoia",
      general_description:
        "The dawn redwood is a fast-growing, deciduous conifer. Though it was once thought to be extinct, living specimens were discovered in China in the 1940s.",
      habitat: "Native to the Sichuan-Hubei region of China",
      isResearched: true,
      conservation_status: "Endangered",
      fundingGoal: 2.5,
      fundingRaised: 2.0,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "white-oak",
      common_name: "White Oak",
      accepted_scientific_name: "Quercus alba",
      species: "alba",
      family: "Fagaceae",
      genus: "Quercus",
      general_description:
        "The white oak is a long-lived oak in the white oak group. It is native to eastern and central North America and is renowned for its high-quality wood.",
      habitat: "Native to eastern and central North America",
      isResearched: true,
      conservation_status: "Least Concern",
      fundingGoal: 1.0,
      fundingRaised: 0.8,
      image: "/placeholder.svg?height=600&width=800",
    },
    {
      taxon_id: "ginkgo",
      common_name: "Ginkgo",
      accepted_scientific_name: "Ginkgo biloba",
      species: "biloba",
      family: "Ginkgoaceae",
      genus: "Ginkgo",
      general_description:
        "The ginkgo is a unique species of tree with no close living relatives. It is a living fossil, with fossils recognizably related to modern ginkgo from the Permian period, dating back 270 million years.",
      habitat: "Native to China, but widely cultivated around the world",
      isResearched: true,
      conservation_status: "Endangered",
      fundingGoal: 2.0,
      fundingRaised: 1.5,
      image: "/placeholder.svg?height=600&width=800",
    },
  ]
  
  // Treederboard mock data
  export const mockLeaderboard = [
    {
      id: 1,
      wallet_address: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
      display_name: "TreeMaster",
      total_points: 12500,
      contribution_count: 42,
      first_contribution_at: "2023-01-15T12:00:00Z",
      last_contribution_at: "2023-12-20T15:30:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 1,
    },
    {
      id: 2,
      wallet_address: "0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c",
      display_name: "ForestKeeper",
      total_points: 10750,
      contribution_count: 36,
      first_contribution_at: "2023-02-10T09:15:00Z",
      last_contribution_at: "2023-12-15T11:45:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 2,
    },
    {
      id: 3,
      wallet_address: "0x3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d",
      display_name: "ArborExplorer",
      total_points: 9800,
      contribution_count: 33,
      first_contribution_at: "2023-01-20T14:30:00Z",
      last_contribution_at: "2023-12-10T16:20:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 3,
    },
    {
      id: 4,
      wallet_address: "0x4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e",
      display_name: "GreenThumb",
      total_points: 8200,
      contribution_count: 28,
      first_contribution_at: "2023-03-05T10:45:00Z",
      last_contribution_at: "2023-12-05T13:10:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 4,
    },
    {
      id: 5,
      wallet_address: "0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f",
      display_name: "LeafCollector",
      total_points: 7500,
      contribution_count: 25,
      first_contribution_at: "2023-02-25T08:20:00Z",
      last_contribution_at: "2023-11-30T09:50:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 5,
    },
    {
      id: 6,
      wallet_address: "0x6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a",
      display_name: "BotanistPro",
      total_points: 6800,
      contribution_count: 23,
      first_contribution_at: "2023-04-10T11:30:00Z",
      last_contribution_at: "2023-11-25T14:40:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 6,
    },
    {
      id: 7,
      wallet_address: "0x7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b",
      display_name: "WoodlandWalker",
      total_points: 5900,
      contribution_count: 20,
      first_contribution_at: "2023-03-15T13:45:00Z",
      last_contribution_at: "2023-11-20T10:15:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 7,
    },
    {
      id: 8,
      wallet_address: "0x8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c",
      display_name: "NatureFriend",
      total_points: 5200,
      contribution_count: 18,
      first_contribution_at: "2023-05-05T09:10:00Z",
      last_contribution_at: "2023-11-15T15:30:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 8,
    },
    {
      id: 9,
      wallet_address: "0x9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d",
      display_name: "TreeHugger",
      total_points: 4600,
      contribution_count: 16,
      first_contribution_at: "2023-04-20T14:20:00Z",
      last_contribution_at: "2023-11-10T12:45:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 9,
    },
    {
      id: 10,
      wallet_address: "0xa0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9",
      display_name: "EcoWarrior",
      total_points: 4100,
      contribution_count: 14,
      first_contribution_at: "2023-06-10T10:30:00Z",
      last_contribution_at: "2023-11-05T11:20:00Z",
      avatar: "/placeholder.svg?height=40&width=40",
      rank: 10,
    },
  ]
  
  // User profile mock data
  export const mockUserProfile = {
    id: 42,
    wallet_address: "0x1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b",
    display_name: "Alex Johnson",
    username: "TreeEnthusiast",
    bio: "Tree lover and conservation advocate. I'm passionate about preserving our forests for future generations.",
    total_points: 3250,
    contribution_count: 8,
    rank: 42,
    first_contribution_at: "2023-05-15T09:30:00Z",
    last_contribution_at: "2023-10-20T14:15:00Z",
    avatar: "/placeholder.svg?height=200&width=200",
    banner: "/placeholder.svg?height=400&width=1200&text=Profile Banner",
    walletConnected: true,
    nfts: [
      {
        id: 1,
        global_id: 101,
        taxon_id: "giant-sequoia",
        points: 500,
        ipfs_cid: "ipfs://bafybeihbmin5h7ektpjqgr7rdnmtxcaujjgxcxz6nu5ynvkqirtbxj7xt4",
        transaction_hash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
        created_at: "2023-05-15T09:30:00Z",
        metadata: {
          name: "Giant Sequoia #042",
          species: "Giant Sequoia",
          image: "/placeholder.svg?height=300&width=300&text=NFT 1",
        },
      },
      {
        id: 2,
        global_id: 102,
        taxon_id: "baobab",
        points: 500,
        ipfs_cid: "ipfs://bafybeihbmin5h7ektpjqgr7rdnmtxcaujjgxcxz6nu5ynvkqirtbxj7xt5",
        transaction_hash: "0x2345678901abcdef2345678901abcdef2345678901abcdef2345678901abcdef",
        created_at: "2023-06-22T11:45:00Z",
        metadata: {
          name: "Baobab #128",
          species: "Baobab",
          image: "/placeholder.svg?height=300&width=300&text=NFT 2",
        },
      },
      {
        id: 3,
        global_id: 103,
        taxon_id: "japanese-maple",
        points: 500,
        ipfs_cid: "ipfs://bafybeihbmin5h7ektpjqgr7rdnmtxcaujjgxcxz6nu5ynvkqirtbxj7xt6",
        transaction_hash: "0x3456789012abcdef3456789012abcdef3456789012abcdef3456789012abcdef",
        created_at: "2023-07-10T14:20:00Z",
        metadata: {
          name: "Japanese Maple #076",
          species: "Japanese Maple",
          image: "/placeholder.svg?height=300&width=300&text=NFT 3",
        },
      },
      {
        id: 4,
        global_id: 104,
        taxon_id: "weeping-willow",
        points: 500,
        ipfs_cid: "ipfs://bafybeihbmin5h7ektpjqgr7rdnmtxcaujjgxcxz6nu5ynvkqirtbxj7xt7",
        transaction_hash: "0x4567890123abcdef4567890123abcdef4567890123abcdef4567890123abcdef",
        created_at: "2023-08-05T10:10:00Z",
        metadata: {
          name: "Weeping Willow #103",
          species: "Weeping Willow",
          image: "/placeholder.svg?height=300&width=300&text=NFT 4",
        },
      },
    ],
  }
  
  