-- Alter table to change data types for species table columns
ALTER TABLE species ALTER COLUMN species TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN family TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN genus TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN subspecies TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN common_name TYPE VARCHAR(200);
ALTER TABLE species ALTER COLUMN accepted_scientific_name TYPE VARCHAR(200);
ALTER TABLE species ALTER COLUMN common_countries TYPE TEXT;
ALTER TABLE species ALTER COLUMN class TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN taxonomic_order TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN ecoregions TYPE TEXT;
ALTER TABLE species ALTER COLUMN biomes TYPE TEXT;
ALTER TABLE species ALTER COLUMN conservation_status TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN general_description TYPE TEXT;
ALTER TABLE species ALTER COLUMN associated_media TYPE TEXT;
ALTER TABLE species ALTER COLUMN ecological_function TYPE TEXT;
ALTER TABLE species ALTER COLUMN elevation_ranges TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN compatible_soil_types TYPE TEXT;
ALTER TABLE species ALTER COLUMN default_image TYPE VARCHAR(255);
ALTER TABLE species ALTER COLUMN habitat TYPE TEXT;
ALTER TABLE species ALTER COLUMN total_occurrences TYPE INT USING (NULLIF(total_occurrences, 'NA')::INT);
ALTER TABLE species ALTER COLUMN specific_epithet TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN synonyms TYPE TEXT;
ALTER TABLE species ALTER COLUMN bioregions TYPE TEXT;
ALTER TABLE species ALTER COLUMN countries_introduced TYPE TEXT;
ALTER TABLE species ALTER COLUMN countries_invasive TYPE TEXT;
ALTER TABLE species ALTER COLUMN countries_native TYPE TEXT;
ALTER TABLE species ALTER COLUMN forest_type TYPE TEXT;
ALTER TABLE species ALTER COLUMN wetland_type TYPE TEXT;
ALTER TABLE species ALTER COLUMN urban_setting TYPE TEXT;
ALTER TABLE species ALTER COLUMN climate_change_vulnerability TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN associated_species TYPE TEXT;
ALTER TABLE species ALTER COLUMN native_adapted_habitats TYPE TEXT;
ALTER TABLE species ALTER COLUMN agroforestry_use_cases TYPE TEXT;
ALTER TABLE species ALTER COLUMN successional_stage TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN tolerances TYPE TEXT;
ALTER TABLE species ALTER COLUMN forest_layers TYPE TEXT;
ALTER TABLE species ALTER COLUMN growth_form TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN leaf_type TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN deciduous_evergreen TYPE VARCHAR(20);
ALTER TABLE species ALTER COLUMN flower_color TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN fruit_type TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN bark_characteristics TYPE TEXT;
ALTER TABLE species ALTER COLUMN maximum_height TYPE DECIMAL(10,2) USING (NULLIF(maximum_height, 'NA')::DECIMAL);
ALTER TABLE species ALTER COLUMN maximum_diameter TYPE DECIMAL(10,2) USING (NULLIF(maximum_diameter, 'NA')::DECIMAL);
ALTER TABLE species ALTER COLUMN lifespan TYPE VARCHAR(50);
ALTER TABLE species ALTER COLUMN maximum_tree_age TYPE INT USING (NULLIF(maximum_tree_age, 'NA')::INT);
ALTER TABLE species ALTER COLUMN allometric_models TYPE TEXT;
ALTER TABLE species ALTER COLUMN allometric_curve TYPE TEXT;
ALTER TABLE species ALTER COLUMN national_conservation_status TYPE TEXT;
ALTER TABLE species ALTER COLUMN verification_status TYPE VARCHAR(20);
ALTER TABLE species ALTER COLUMN threats TYPE TEXT;
ALTER TABLE species ALTER COLUMN timber_value TYPE TEXT;
ALTER TABLE species ALTER COLUMN non_timber_products TYPE TEXT;
ALTER TABLE species ALTER COLUMN cultural_significance TYPE TEXT;
ALTER TABLE species ALTER COLUMN cultivars TYPE TEXT;
ALTER TABLE species ALTER COLUMN nutritional_caloric_value TYPE TEXT;
ALTER TABLE species ALTER COLUMN cultivation_details TYPE TEXT;
ALTER TABLE species ALTER COLUMN stewardship_best_practices TYPE TEXT;
ALTER TABLE species ALTER COLUMN planting_recipes TYPE TEXT;
ALTER TABLE species ALTER COLUMN pruning_maintenance TYPE TEXT;
ALTER TABLE species ALTER COLUMN disease_pest_management TYPE TEXT;
ALTER TABLE species ALTER COLUMN fire_management TYPE TEXT;
ALTER TABLE species ALTER COLUMN reference_list TYPE TEXT;
ALTER TABLE species ALTER COLUMN data_sources TYPE TEXT;
ALTER TABLE species ALTER COLUMN ipfs_cid TYPE VARCHAR(100);
ALTER TABLE species ALTER COLUMN last_updated_date TYPE TIMESTAMP USING (NULLIF(last_updated_date, 'NA')::TIMESTAMP);