- name: Destroy DigitalOcean Droplet with Blazegraph
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    droplet_name: blazegraph-droplet

  tasks:
    - name: Get the list of droplets
      community.digitalocean.digital_ocean_droplet_info:
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
      register: droplets_info

    - name: Find the droplet to destroy
      set_fact:
        droplet_id: "{{ item.id }}"
      loop: "{{ droplets_info.data|selectattr('name', 'equalto', droplet_name)|list }}"
      when: item.name == droplet_name

    - name: Destroy the droplet
      community.digitalocean.digital_ocean_droplet:
        state: absent
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        id: "{{ droplet_id }}"
      when: droplet_id is defined

