---
- name: Provision and Configure DigitalOcean Droplet with Blazegraph
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    droplet_name: blazegraph-droplet
    region: nyc3
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
  tasks:
    - name: Create a new DigitalOcean droplet
      community.digitalocean.digital_ocean_droplet:
        state: present
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        name: "{{ droplet_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        image: "{{ image }}"
        ssh_keys: ["{{ lookup('env', 'DO_SSH_KEY_ID') }}"]
      register: droplet

    - name: Output Droplet Information
      debug:
        msg:
          - "Droplet Name: {{ droplet.data.droplet.name }}"
          - "Droplet IP: {{ droplet.data.droplet.networks.v4[0].ip_address }}"
          - "Droplet Region: {{ droplet.data.droplet.region.name }}"
          - "Droplet Status: {{ droplet.data.droplet.status }}"

    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ droplet.data.droplet.networks.v4[0].ip_address }}"
        port: 22
        timeout: 300
        state: started

    - name: Add droplet IP to dynamic inventory
      add_host:
        name: "{{ droplet.data.droplet.networks.v4[0].ip_address }}"
        groups: provisioned_droplets
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ansible/digitalocean.pem
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

- name: Configure Droplet and Set Up Blazegraph
  hosts: provisioned_droplets
  become: yes
  vars:
    blazegraph_url: https://repo1.maven.org/maven2/com/blazegraph/blazegraph-jar/2.1.5/blazegraph-jar-2.1.5.jar
    blazegraph_dest: /opt/blazegraph.jar
  tasks:
    # - name: Wait for apt lock to be released
    #   command: |
    #     bash -c 'while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done'

    - name: Kill process holding apt lock (if necessary)
      shell: |
        kill -9 $(lsof -t /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock) 2>/dev/null || true

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Java (Blazegraph dependency)
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Download Blazegraph
      get_url:
        url: "{{ blazegraph_url }}"
        dest: "{{ blazegraph_dest }}"
        mode: '0755'

    - name: Create a systemd service for Blazegraph
      copy:
        dest: /etc/systemd/system/blazegraph.service
        content: |
          [Unit]
          Description=Blazegraph Database
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/bin/java -server -jar {{ blazegraph_dest }}
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and start Blazegraph
      systemd:
        daemon_reload: yes
        name: blazegraph
        state: started
        enabled: yes
  