import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ResearchProvider } from "@/context/research-context";
import Providers from "./providers";



const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <Providers>
          <ResearchProvider>{children}</ResearchProvider>
        </Providers>
        </body>
    </html>
  );
}
